spring:
  profiles:
    active: local

---
spring:
  profiles:
    active: local
  mail:
    host: smtp.abv.bg
    port: 465
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url:  "jdbc:mysql://localhost:3306/lozev?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true"
#    username:  ${JDBC_DATABASE_USERNAME:root}
#    password: ${JDBC_DATABASE_PASSWORD:root}

  #  sql:
  #    init:
  #      mode: always


#  jpa:
#    # Choose either MySQL 8 or MySQL 5 below
#    # For MySQL 8
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    #For MySQL 5
#    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    #database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#    open-in-view: false
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    #root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: ["*"]
      base-path: "/admin"
  server:
    port: 8081

